---
  - name: Update package cache
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: "{{ update_cache_valid_time }}"

  - name: Upgrade packages
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: Remove useless packages from the cache
    ansible.builtin.apt:
      autoclean: yes

  - name: Purge dependencies that are no longer required
    ansible.builtin.apt:
      autoremove: "{{ update_autoremove }}"
      purge: "{{ update_autoremove_purge }}"
