---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: deb10-instance
    image: qwe1/docker-debian:buster-slim-nonfree-molecule
    pre_build_image: true
  - name: deb11-instance
    image: qwe1/docker-debian:bullseye-slim-nonfree-molecule
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
