---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: deb12-instance
    image: qwe1/docker-debian:bookworm-slim-nonfree-molecule
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
